version: '3'

services:
  golang:
    image: golang:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/app/src
    ports:
      - "9090:8080"
    environment:
      - TZ=Asia/Shanghai
      - GO111MODULE=on
      - GOPROXY=https://goproxy.io
    container_name: mall
    command: bash -c "cd /app/src && go run main.go"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mall-mongo


    ports:
      - "29917:27017"
    volumes:
      - ./data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=mall

